name: First Python CI
run-name: Python CI, triggered by ${{ github.event_name }}
on: [push, pull_request]
jobs:
    plot:
        name: Plot
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run pylint
              run: |
                pylint --disable=import-outside-toplevel mandelbrot.py
            - name: Generate the mandelbrot set
              run: |
                python mandelbrot.py --pdf
            - name: Output as Artifact
              uses: actions/upload-artifact@v4
              with:
                name: mandelbrot
                path: mandelbrot.pdf
                retention-days: 1
                if-no-files-found: error
 
